import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="navbar">
        <Link href={'/'} className="logo">JJopForum</Link>
        <div className="nav_eles">
        <Link href={'/community'} className="nav_ele">List</Link>
        <Link href={'/write'} className="nav_ele">Write</Link>
        </div>
      </div>
        {children}
      </body>
    </html>
  );
}
