import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
    <meta charSet="UTF-8"/>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="navbar">
        <Link href="/">홈</Link>
        <Link href="/list">상품</Link>
        <Link href="/cartlist">장바구니</Link>
      </div>
        {children}
      </body>
    </html>
  );
}
